# Serves as the .pre-commit-config.yaml of the repo, as well as a baseline template for reuse

repos:

  ### Secrets protection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

  ### General
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # File formatting
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # Large files (set file size)
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      # Executables:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # JSON files:
      - id: check-json
      # - id: pretty-format-json
      #   args: ["--autofix", "--indent=4", "--top-keys='key,command'"]

  ### Shell scripting
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
        # Matches options in .shellcheckrc
        args: ["--shell=bash", "-x", "--exclude=SC1090,SC1091,SC2164"]

  ### C++
  # - repo: https://github.com/pre-commit/mirrors-clang-format
  #   rev: v20.1.8
  #   hooks:
  #   - id: clang-format

  ### LaTeX Formatting
  # - repo: https://github.com/cmhughes/latexindent.pl.git
  #   rev: V3.24.7
  #   hooks:
  #     - id: latexindent
  #       # Matches args for latexindent in VS Code settings
  #       args: ["-wd", "-s", "-m", "-y=defaultIndent:'  ',modifyLineBreaks:textWrapOptions:columns:100"]
